---

default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
        stages: [pre-commit, manual]
      # Replaces or checks mixed line ending.
      - id: mixed-line-ending
        # Checks if there is any mixed line ending without modifying any file.
        args: [--fix=no]
      # Trims trailing whitespace.
      - id: trailing-whitespace
        # Preserve Markdown linebreaks
        args: [--markdown-linebreak-ext=md]
        stages: [pre-commit, manual]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      # Fix common misspellings in source code
      - id: codespell
        entry: codespell --write-changes
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      # YAML linter
      - id: yamllint
        args: [--config-data, "{extends: relaxed, rules: {line-length: {max: 100}}}"]
