---

- name: enable the Docker SystemD service
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html
  systemd:
    name: docker
    enabled: true
    state: started
