---

- name: create the binary directory
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  file:
    owner: root
    group: root
    path: "{{ ewgq_bin_dir }}"
    state: directory
    mode: 0755

- name: download the script
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
  get_url:
    dest: "{{ ewgq_bin_dir }}/easy-wg-quick"
    owner: root
    group: root
    mode: 0750
    url: "https://raw.githubusercontent.com/burghardt/easy-wg-quick/master/easy-wg-quick"

- name: create the data directory
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  file:
    owner: root
    group: root
    path: "{{ ewgq_etc_dir }}"
    state: directory
    mode: 0700

- name: set the default network range
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
  copy:
    content: "/24"
    dest: "{{ ewgq_etc_dir }}/intnetmask.txt"
    mode: 0640

- name: install extra dependencies
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
  apt:
    state: present
    pkg:
      - qrencode

- name: generate the easy-wg-quick configuration, unless present
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  command:
    chdir: "{{ ewgq_etc_dir }}"
    cmd: "{{ ewgq_bin_dir }}/easy-wg-quick"
    creates: "{{ ewgq_etc_dir }}/wghub.conf"

- name: Enable the SystemD service for easy-wg-quick
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html
  systemd:
    name: wg-quick@wghub
    enabled: true
